# Generated by Django 6.0 on 2025-12-11 02:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Mesa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero", models.PositiveIntegerField(unique=True)),
                ("capacidad", models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Reserva",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre_cliente", models.CharField(max_length=100)),
                ("telefono", models.CharField(max_length=15)),
                ("fecha_reserva", models.DateField()),
                ("hora_reserva", models.TimeField()),
                ("cantidad_personas", models.PositiveIntegerField()),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("RESERVADO", "Reservado"),
                            ("COMPLETADA", "Completada"),
                            ("ANULADA", "Anulada"),
                            ("NO_ASISTEN", "No asisten"),
                        ],
                        default="RESERVADO",
                        max_length=12,
                    ),
                ),
                ("observacion", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "mesa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reservas",
                        to="reservas.mesa",
                    ),
                ),
            ],
        ),
    ]
