# Generated by Django 6.0 on 2025-12-11 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservas", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="reserva",
            constraint=models.UniqueConstraint(
                fields=("mesa", "fecha_reserva", "hora_reserva"),
                name="uniq_reserva_mesa_fecha_hora",
            ),
        ),
    ]
