# Generated by Django 6.0 on 2025-12-11 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reservas", "0002_reserva_uniq_reserva_mesa_fecha_hora"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="reserva",
            name="uniq_reserva_mesa_fecha_hora",
        ),
    ]
